accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Index.as_view(), name = 'index'),
  #path('login/',views.login, name = 'login')
  path('contactUs/', views.contactus2, name="contactus"),

  #Authentication Endpoints
  path('signup/', views.RegisterView.as_view(), name="signup"),
  path('login/', views.LoginViewUser.as_view(redirect_authenticated_user=True), name="login"),
  path('logout/', views.LogoutViewUser.as_view(), name="logout"),
  path('activate/<uidb64>/<token>', views.activate, name='activate'),
  
  #profile endpoints
  path('profile/', views.profile, name = 'profile'),
]

openbanking/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('sr/', include('User_Accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
#to store data as form obj, and not as string(optional)
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator
from .managers import CustomUserManager
from django.utils import timezone
from django.contrib.auth.models import PermissionsMixin #optional -> to be used for AbstractBaseUser

class LowercaseEmailField(models.EmailField):
    """
    Override EmailField to convert emails to lowercase before saving.
    """
    def to_python(self, value):
        """
        Convert email to lowercase.
        """
        value = super(LowercaseEmailField, self).to_python(value)
        # Value can be None so check that it's a string before lowercasing.
        if isinstance(value, str):
            return value.lower()
        return value

class CustomUser(AbstractUser):
  username = None
  email = LowercaseEmailField(_('email address'), unique=True)
  name = models.CharField(max_length=255)
  is_staff = models.BooleanField(default=False)
  is_active = models.BooleanField(default=True)
  date_joined = models.DateTimeField(default=timezone.now)



  phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
  phone = models.CharField(max_length=255, validators=[phone_regex], blank = True, null=True,unique = True)
  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = []

  objects = CustomUserManager()

  def __str__(self):
    return self.email

class Contact(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=5)
    phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    phone = models.CharField(max_length=255, validators=[phone_regex])
    query = models.TextField()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db.models import fields

from .models import CustomUser,Contact

from django import forms
from django.core.validators import RegexValidator

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)



class ContactUsForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'email',
            'phone',
            'query',
            'name'
        ]




class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = [
            'email',
            'name',
            'phone',
            'password1',
            'password2',
        ]


class SendOtpBasicForm(forms.Form):
    phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    phone = forms.CharField(max_length=255, validators=[phone_regex])

    class Meta:
        fields = [
            'phone',
        ]

class VerifyOtpBasicForm(forms.Form):
    otp_regex = RegexValidator( regex = r'^\d{4}$',message = "otp should be in six digits")
    otp = forms.CharField(max_length=6, validators=[otp_regex])

accounts/views.py
from django.shortcuts import render, HttpResponse, redirect

from django.urls import reverse_lazy, reverse
from django.views.generic.base import TemplateView
from .forms import RegistrationForm, ContactUsForm
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from .models import CustomUser

from openbanking import settings
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


# Create your views here.


class Index(TemplateView):
    template_name = 'accounts/index.html'


def contactus2(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():  # clean_data
            if len(form.cleaned_data.get('query')) > 10:
                form.add_error('query', 'Query length is not right')
                return render(request, 'accounts/contactUs.html', {'form': form})
            form.save()
            return HttpResponse("Thank You")
        else:
            if len(form.cleaned_data.get('query')) > 10:
                #form.add_error('query', 'Query length is not right')
                form.errors['__all__'] = 'Query length is not right. It should be in 10 digits.'
            return render(request, 'accounts/contactUs.html', {'form': form})
    return render(request, 'accounts/contactUs.html', {'form': ContactUsForm})


class RegisterView(CreateView):
    template_name = 'accounts/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('login')

    # def post(self, request, *args, **kwargs):
    #     #form = RegistrationForm(request.POST)
    #     response = super().post(request, *args, **kwargs)
    #     user_email = request.POST.get('email')

    #     if response.status_code == 200:
    #         user = CustomUser.objects.get(email = user_email)
    #         user.is_active = False
    #         user.save()
    #         current_site = get_current_site(request)
    #         mail_subject = 'Activate your account.'
    #         message = render_to_string('accounts/registration/acc_active_email.html', {
    #             'user': user,
    #             'domain': current_site.domain,
    #             'uid':urlsafe_base64_encode(force_bytes(user.pk)),
    #             'token':account_activation_token.make_token(user),
    #         })
    #         print(message)
    #         to_email = user_email
    #         #form = RegistrationForm(request.POST)   # here we are again calling all its validations
    #         form = self.get_form()
    #         try:
    #             send_mail(
    #                 subject=mail_subject,
    #                 message=message,
    #             from_email=settings.EMAIL_HOST_USER,
    #             recipient_list= [to_email],
    #             fail_silently=False,    # if it fails due to some error or email id then it get silenced without affecting others
    #         )
    #         messages.success(request, "link has been sent to your email id. please check your inbox and if its not there check your spam as well.")
    #         return self.render_to_response({'form':form})
    #     except:
    #         form.add_error('', 'Error Occured In Sending Mail, Try Again')
    #         messages.error(request, "Error Occured In Sending Mail, Try Again")
    #         return self.render_to_response({'form':form})
    # else:
    #     return response


class LoginViewUser(LoginView):
    template_name = "accounts/login.html"

class LogoutViewUser(LogoutView):
    success_url = reverse_lazy('index')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist) as e:
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "Successfully Logged In")
        return redirect(reverse_lazy('index'))
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid or your account is already Verified! Try To Login')

# @login_required(login_url='login')
def logoutUser(request):
    logout(request)
    return redirect('/login')

# @login_required(login_url='login/')
def profile(request):
    # return render(request, 'accounts/profile.html')
    return render(request, 'account_det.html')

accounts/templates/accounts/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>{% block title %}
  {% endblock %}</title>
  {% block css %} {% endblock %}
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">FG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href={% url 'index' %}>Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'contactus' %}>Contact Us</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href={% url 'account_det' %}>My Profile</a>
            <a class="dropdown-item" href={% url 'reg' %}>Add Account</a>
            <div class="dropdown-divider"></div>
            <a href={% url 'logout' %} class="dropdown-item">Logout</a>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>

    {% else %}

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href={% url 'login' %}>Login <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'signup' %}>Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'contactus' %}>Contact Us</a>
        </li>
      </ul>
    </div>
    {% endif %}
  </nav>

  {% if messages %}
  {% for message in messages %}
  <div class="text-center alert alert-{{ message.tags }} alert-dismissible fade show" role="alert"
    style="margin-bottom:0px;">
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
  {% endif %}

  {% block body %}
  {% endblock %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>
{% block js %}{% endblock %}

</html>

accounts/templates/accounts/base_profile.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}{% endblock  %}</title>
    {% block css %} {% endblock %} 
  </head>
  <body>
  
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/logout/">Logout <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/signup/">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contactUs">Contact Us</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

{% block body %}
{% endblock  %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
  {% block js %}{% endblock  %}
</html>

accounts/templates/accounts/contactUs.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}

{% block body%}
<div class="container">
<form method="POST">{% csrf_token %}
<!--{{form.as_p}} -->
{{ form.non_field_errors }}
      <label for="id_email" class="login-labels">Email Address*</label> 
      {{ form.email.errors }}
      {{ form.email|addclass:'form-control'|addplaceholder:'Email Address'}}
      
      <label for="id_phone" class="login-labels">Phone No.*</label> 
      {{ form.phone.errors }}
      {{ form.phone|addclass:'form-control'|addplaceholder:'Phone number' }}
      <label for="id_query" class="login-labels">Query*</label> 
      {{ form.query.errors }}
      {{ form.query|addclass:'form-control'|addplaceholder:'Any Query' }}
      <label for="id_name" class="login-labels">Name*</label> 
      {{ form.name.errors }}
      {{ form.name|addclass:'form-control'|addplaceholder:'Your Name' }}
<button type="submit" class="btn btn-primary">Submit</button>
</form>

</div>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}
{% endblock  %}
{% block css %}
{% endblock  %}
{% block body %}
<h1>HOME PAGE : FG</h1>
{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}
{% block body %}

<main id="main">
  <div class="container" id="login">
    <div class="row justify-content-center">
      <div class="col-md-6 col-sm-12 col-xs-12">
        <div class="form-login">
          <form method="POST">
            {% csrf_token %}
                  <div class="main-area">
                        <div class="register-form">
                              {{ form.non_field_errors }}
                              <h2 class="mainheading"> Fintract </h2>
                              <h4 class="mainheading">Login</h4>
                              <label for="id_username" class="login-labels">Email Address*</label>
                              {{ form.username.errors }}
                              {{ form.username|addclass:'form-control'|addplaceholder:'Email Address'}}
                              <label for="id_password" class="login-labels">Password*</label>
                              {{ form.password.errors }}
                              {{ form.password|addclass:'form-control'|addplaceholder:'Your Password' }}
                              <br>
                              <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off"> Submit
                              </button>
            </form>

          <form action="{% url 'signup' %}">
            <button class="btn btn-sign-up" type="submit">
              New User? Sign Up <i class="fa fa-arrow-right"></i>
            </button>
          </form>
        </div>
      </div>
    </div>
    </div>
  <br />
</main>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base_profile.html' %}
{% load static %}
{% block title %}
{% endblock  %}
{% block css %}
{% endblock  %}
{% block body %}
Profile Page
{% endblock  %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}
{% endblock  %}
{% block css %}
{% endblock  %}
{% block body %}
<main id="main">
  <div class="container" id="sign-up">
    <div class="row">
      <div class="col-md-6 col-sm-12 col-xs-12">
        <h1>Sign Up</h1>
        <div class="form-sign">
          {{ form.non_field_errors }}
            <form method="POST">{% csrf_token %}
                {{form.as_p}}

                <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off"> Submit
                              </button>
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock  %}